
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkzbybyotyozggqfkxvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhremJ5YnlvdHlvemdncWZreHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDQyODQsImV4cCI6MjA1ODkyMDI4NH0.htXVKC6QAdMl7DxST0G0fcId02vl6Rsyw6EjbvpKn-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a helper function to check if a table exists
export const tableExists = async (tableName: string): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from('pg_tables')
      .select('tablename')
      .eq('schemaname', 'public')
      .eq('tablename', tableName)
      .single();
    
    return !error && !!data;
  } catch (error) {
    console.error('Error checking if table exists:', error);
    return false;
  }
};
